-- View 6 : Extra
--Create a view for calculating the Client Lifetime Value (LTV)
--LTV shows the totals sales generated by each client over ...
--their lifetime with the company based on exisiting purchases
--to calculate this we calculate: total nbr times bought, total lifetime sales, avg sales per invoice

CREATE VIEW view_6 AS
SELECT c.name as client_name, 
	COUNT(DISTINCT i.id_invoice) as total_nbr_invoices, 
	TO_CHAR(SUM(ip.quantity * p.price), '€FM999G999G999D00') as total_lifetime_sales, 
	TO_CHAR(AVG(ip.quantity * p.price), '€FM999G999G999D00') as avg_sales_per_invoice
FROM client c INNER JOIN branch b USING (id_client)
	INNER JOIN invoice i USING (id_branch)
	INNER JOIN invoice_products ip USING (id_invoice)
	INNER JOIN product p USING (id_prod)
GROUP BY 1
ORDER BY 2 DESC
;

-- MetroCare is the best client (lifetime) with 372 purchases and a total sales of 87876.86 euros
--and an average sale per invoice of 236.23 euros
